"""weathers2

Revision ID: 3a5960d4d538
Revises: 004d669eb6e6
Create Date: 2023-10-24 00:49:42.165026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5960d4d538'
down_revision: Union[str, None] = '004d669eb6e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weathers', sa.Column('degree', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weathers', 'degree')
    # ### end Alembic commands ###
