"""weathers

Revision ID: d94dcc7fa934
Revises: 3a5960d4d538
Create Date: 2023-10-24 12:16:17.543158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94dcc7fa934'
down_revision: Union[str, None] = '3a5960d4d538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weathers', sa.Column('date', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weathers', 'date')
    # ### end Alembic commands ###
