"""weathers4

Revision ID: 89061ad824b2
Revises: d94dcc7fa934
Create Date: 2023-10-27 14:52:00.459490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89061ad824b2'
down_revision: Union[str, None] = 'd94dcc7fa934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weathers', sa.Column('temperature', sa.Integer(), nullable=False))
    op.add_column('weathers', sa.Column('pressure', sa.Integer(), nullable=False))
    op.add_column('weathers', sa.Column('wind', sa.Float(), nullable=False))
    op.drop_column('weathers', 'degree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weathers', sa.Column('degree', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('weathers', 'wind')
    op.drop_column('weathers', 'pressure')
    op.drop_column('weathers', 'temperature')
    # ### end Alembic commands ###
